# Generated by Django 2.1.4 on 2018-12-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comm',
        ),
        migrations.AlterField(
            model_name='mark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Article', verbose_name='Статья'),
        ),
    ]
