# Generated by Django 2.1.4 on 2018-12-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181220_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='author_article', to='webapp.User'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='comm',
        ),
        migrations.AddField(
            model_name='article',
            name='comm',
            field=models.ManyToManyField(related_name='comment', to='webapp.Comment'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='marks',
        ),
        migrations.AddField(
            model_name='article',
            name='marks',
            field=models.ManyToManyField(related_name='mark', to='webapp.Mark'),
        ),
    ]
