# Generated by Django 2.1.4 on 2018-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181220_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Содержимое')),
                ('date', models.DateField(verbose_name='Дата')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='webapp.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_comment', to='webapp.User')),
            ],
        ),
    ]
